version: '3.7'

services:
  jaeger:
    image: johanneswuerbach/jaeger-dynamodb
    build: .
    hostname: jaeger
    environment:
      - GRPC_STORAGE_PLUGIN_LOG_LEVEL=debug
      - SPAN_STORAGE_TYPE=grpc-plugin
      - GRPC_STORAGE_PLUGIN_BINARY=/go/bin/dynamodb-plugin
      - AWS_PROFILE
      - AWS_REGION
    volumes:
      - ~/.aws:/root/.aws
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  hotrod:
    image: jaegertracing/example-hotrod:latest
    ports:
      - "8080:8080"
    command: ["all"]
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - jaeger

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]

  test:
    build:
      context: .
      target: test
    environment:
      - DYNAMODB_URL=http://dynamodb:8000
    depends_on:
      - dynamodb
    volumes:
      - int-mod-cache:/go/pkg/mod
      - int-build-cache:/root/.cache/go-build

  test-integration:
    build:
      context: .
      target: integration
    depends_on:
      - dynamodb
    environment:
      - GRPC_STORAGE_PLUGIN_LOG_LEVEL=debug
      - PLUGIN_BINARY_PATH=/go/bin/dynamodb-plugin
      - PLUGIN_CONFIG_PATH=/test-config.yml
      - STORAGE=grpc-plugin
    volumes:
      - int-mod-cache:/go/pkg/mod
      - int-build-cache:/root/.cache/go-build
      - ./test-config.yml:/test-config.yml

volumes:
  int-mod-cache:
  int-build-cache:
